apps/student/urls.py
from django.urls import path, include, re_path
from apps.student import views
from apps.student import datatable_view

app_name = 'student'

urlpatterns = [
    path('create/', views.StudentCreateView.as_view(), name='student_create'),
    path('list/', views.StudentListView.as_view(), name="student_list"), 

    path('details/<int:pk>/', views.StudentDetailsView.as_view(), name="student_details"), 
    path('update/<int:pk>/',  views.StudentUpdateView.as_view(),  name="student_update"), 
    
    # path('delete/', views.StudentDeleteView, name='student_delete'),
    path('delete/', views.StudentDeleteView.as_view(), name='student_delete'),



    ## Data Table
    path('data-table-data/', datatable_view.StudentDatatableList.as_view(), name="student_data_table_data"), 

    # url(r'^my/datatable/data/$', login_required(OrderListJson.as_view()), name='order_list_json'),


    # path('data-table-data/', views.student_data_table_data, name="student_data_table_data"), 

]

apps/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('apps.auth.urls',  namespace='auth')),
    path('', include('apps.dashboards.urls', namespace='dashboards')),
    path('admins/', include('apps.admin.urls', namespace='admins')),
    path('employee/', include('apps.employee.urls', namespace='employee')),
    path('student/', include('apps.student.urls', namespace='student')),


    ## Error 404 and 500 responses
    path("error-404/", TemplateView.as_view(template_name="error/404.html"), name="error_404"),
    path("error-500/", TemplateView.as_view(template_name="error/500.html"), name="error_500"),

]

django_setting_core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.urls')),


    ## For CKeditor
    # path('ckeditor/', include('ckeditor_uploader.urls')),

]




urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/student/models.py
from django.db import models
from apps.core.models import TimestampedModel
from apps.core.models import District


# Create your models here.
class Student(TimestampedModel):
    class SubjectType(models.TextChoices):
        MATHEMATICS  = 'mathematics' , 'Mathematics'
        PSYCHOLOGY   = 'psychology'  , 'Psychology'
        CHEMISTRY    = 'chemistry'   , 'Chemistry'
        MICROBIOLOGY = 'microbiology', 'Microbiology '
        BOTANY       = 'botany' , 'Botany'
        ANATOMY      = 'anatomy', 'Anatomy'
        GEOLOGY      = 'geology', 'Geology'

    class GenderType(models.TextChoices):
        MALE   = 'male'  , 'Male'
        FEMALE = 'female', 'Female'
        OTHER  = 'other' , 'Other'

    id    = models.AutoField(primary_key=True)
    name  = models.CharField(max_length=50)
    phone = models.CharField(max_length=25)
    gender = models.CharField(
        max_length=10, choices=GenderType.choices, null=True, blank=True
    )
    image = models.ImageField(upload_to='Student/Images/', null=True, blank=True)
    cv    = models.FileField(upload_to='Student/CV/', null=True, blank=True)
    dob   = models.DateField(null=True, blank=True)
    city  = models.ForeignKey(District, null=True, blank=True, on_delete=models.SET_NULL)

    roll = models.IntegerField()
    subject = models.CharField(max_length=250, choices=SubjectType.choices, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    is_verified = models.BooleanField(default=False)

    
    class Meta:
        # managed = False
        db_table = 'students'

    def __str__(self):
        return self.name

apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from apps.users.manager import UserManager
import uuid
from apps.core.models import TimestampedModel

import datetime
import secrets
import random

## AbstructBaseUser has provite some default field ( password, last_login, is_active )
class User(AbstractBaseUser, TimestampedModel, PermissionsMixin):

    class GenderType(models.TextChoices):
        MALE   = 'male'
        FEMALE = 'female'
        OTHER  = 'other'

    class UserType(models.TextChoices):
        ADMIN    = 'admin'
        EMPLOYEE = 'employee'

    id        = models.UUIDField( primary_key = True, unique=True, default = uuid.uuid4, editable=False )
    email     = models.EmailField(
                    unique=True,
                    verbose_name="email address",
                    max_length=255,
                )
    phone     = models.CharField(
                    unique=True,
                    verbose_name="phone number",
                    max_length=30,
                    null = True,
                    blank=True
                )
    first_name = models.CharField(max_length=255, null=True, blank=True)
    last_name  = models.CharField(max_length=255, null=True, blank=True)

    gender   = models.CharField(max_length=10, choices=GenderType.choices, null=True, blank=True)
    dob      = models.DateField(null=True, blank=True) 

    image    = models.ImageField(upload_to="ProfileImage/", null=True, blank=True)

    joining     = models.DateField(null=True, blank=True)
    termination = models.DateField(null=True, blank=True)
    user_salary = models.IntegerField(default=0, null=True, blank=True)

    ## User Permission and Roll
    is_active   = models.BooleanField(default = True)
    is_admin    = models.BooleanField(default = False)
    is_verified = models.BooleanField(default = False)

    ## User Address
    address = models.TextField(null=True, blank=True)

    user_type = models.CharField(
        max_length = 10, 
        choices = UserType.choices,
        default = UserType.EMPLOYEE
    )

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    
    def __str__(self):
        return self.email
    
    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        # return True      ## Default
        return self.is_admin

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        # return True      ## Default
        return self.is_admin

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin
    
    # @property
    # def first_name(self):
    #     if self.name:
    #         parts = self.name.rsplit(" ", 1)
    #         return parts[0]

    # @property
    # def last_name(self):
    #     if self.name:
    #         parts = self.name.rsplit(" ", 1)
    #         return parts[1] if len(parts) > 1 else ""

    @property
    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"
    
    @property
    def name(self):
        return f"{self.first_name} {self.last_name}"
    

    @property
    def age(self):
        if self.dob:
            today = datetime.date.today()
            age   = today.year - self.dob.year - ((today.month, today.day) < (self.dob.month, self.dob.day))
            return age
        else:
            return None

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

apps/student/views.py
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy

from django.contrib.auth import get_user_model
User = get_user_model()

from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.sessions.models import Session
from django.contrib import messages

from django.utils.decorators import method_decorator
from django.utils import timezone

from django.db.models.functions import Concat
from django.db.models import Q, Count, F, Value as V, CharField
from django.db.models.functions import ExtractMonth, ExtractYear

from django.http import HttpRequest, HttpResponse, JsonResponse, Http404, HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage
from django.core.exceptions import ValidationError

from datetime import datetime, timedelta
from random import randint

from django.views import View
from django.views import generic


## Custom
from django_setting_core.permission import is_superuser_or_staff, is_superadmin 
from apps.core.utils2 import CustomPaginator, ExcelDataDownload
from apps.student.models import Student
from apps.student.forms import StudentForm
from apps.core.models import District


# Create your views here.
class StudentCreateView(generic.CreateView, LoginRequiredMixin):
    model = Student
    form_class = StudentForm
    template_name = "Student/create.html"
    success_url = reverse_lazy('student:student_list')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        field_errors = {field.name: field.errors for field in form}
        has_errors = any(field_errors.values())

        # print("---------------------")
        # print(f"Field = {field_errors}, HasErrors = {has_errors}")
        # print(f"HasErrors = {has_errors}")
        # print("---------------------")

        return self.render_to_response(self.get_context_data(
                form = form, 
                field_errors = field_errors, 
                has_errors   = has_errors
            ))
    
    

@method_decorator(user_passes_test(is_superuser_or_staff, 
    login_url=reverse_lazy('auth:login')), name='dispatch')
class StudentListView(generic.TemplateView, LoginRequiredMixin):
    template_name = "student/Datatable/list.html"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['subjects'] = Student.SubjectType.choices
        data['citys'] = District.objects.all()
        return data
    
    def get_queryset(self):
        queryset = Student.objects.all()
        return queryset


    def get(self, request, *args, **kwargs):
        qs = self.get_queryset()

        subject_filter  = self.request.GET.get('subject')
        city_filter     = self.request.GET.get('city')
        created_at_from = self.request.GET.get('created_at_from')
        created_at_to   = self.request.GET.get('created_at_to')
        is_verified_filter = self.request.GET.get('is_verified')

        # print("---------------------")
        # print("subject_filter =", subject_filter)
        # print("city_filter =", city_filter)
        # print("is_verified_filter =", is_verified_filter)
        # print("created_at_from =", created_at_from)
        # print("created_at_to =", created_at_to)
        # print("---------------------")


        if subject_filter:
            qs = qs.filter(subject=subject_filter)

        if city_filter:
            qs = qs.filter(city__id=city_filter)

        if is_verified_filter is not None:
            is_verified_filter = is_verified_filter.lower()  # Convert to lowercase
            if is_verified_filter == 'true':
                qs = qs.filter(is_verified=True)
            elif is_verified_filter == 'false':
                qs = qs.filter(is_verified=False)

        if created_at_from:
            created_at_from_date = datetime.strptime(created_at_from, '%Y-%m-%d')
            created_at_from_date = timezone.make_aware(created_at_from_date)
            created_at_from_date = created_at_from_date.replace(hour=0, minute=0, second=0) 
            qs = qs.filter(created_at__gte=created_at_from_date)

        if created_at_to:
            created_at_to_date = datetime.strptime(created_at_to, '%Y-%m-%d')
            created_at_to_date = timezone.make_aware(created_at_to_date)
            created_at_to_date = created_at_to_date.replace(hour=23, minute=59, second=59)  
            qs = qs.filter(created_at__lte=created_at_to_date)

        # print("--------------")
        # print("qs =", qs)
        # print("--------------")

        export_data = ''

        if 'export' in request.GET:
            export_data = qs
        
        elif 'export_all' in request.GET:
            export_data = Student.objects.all()

        if export_data:

            # Prepare the data for Excel export
            if export_data:
                excel_data = [
                    ['S/N', 'Name', 'Roll No', 'Phone', 'Gender', 'City', 'Subject', 'Birth Date', 'Create Date', 'Updated Date', 'Verification Status'],
                ]

                for index, obj in enumerate(export_data, start=1):
                    dob = obj.dob.strftime('%d-%m-%Y') if obj.dob else ''
                    excel_data.append([
                        index,
                        obj.name,
                        obj.roll,
                        obj.phone,
                        obj.gender.capitalize() if obj.gender else '',
                        obj.city.name if obj.city else '',
                        obj.subject,
                        dob,
                        obj.created_at.strftime('%d-%m-%Y %I:%M:%S %p'),
                        obj.updated_at.strftime('%d-%m-%Y %I:%M:%S %p'),
                        'Verified' if obj.is_verified else 'Unverified',
                    ])
                
                excel_exporter = ExcelDataDownload(excel_data, filename='StudentData_export')
                return excel_exporter.generate_response()

        context = self.get_context_data(**kwargs)
        return render(request, self.template_name, context)




"""
    Student Delete
"""
# def StudentDeleteView(request):
#     if request.method == 'POST':
#         std_id = request.POST.get('std_id')

#         print("---------------------")
#         print("std_id =", std_id)
#         print("---------------------")
        
#         try:
#             # Perform deletion operation based on std_id
#             student = Student.objects.get(id=std_id)
#             student.delete()
#             return JsonResponse({'success': True})
#         except Student.DoesNotExist:
#             return JsonResponse({'success': False, 'error': 'Student not found'})
        

@method_decorator(user_passes_test(is_superuser_or_staff, 
    login_url=reverse_lazy('auth:login')), name='dispatch')
class StudentDeleteView(generic.DeleteView, LoginRequiredMixin):
    model = Student
    # success_url = reverse_lazy('admins:admin_list')

    def post(self, request, *args, **kwargs):
        std_id = request.POST.get('std_id', None)
      
        if std_id is not None:
            try:
                std = Student.objects.get(id = std_id)
                if std:
                    std.delete()
                    return JsonResponse({'success': True})
            except Student.DoesNotExist:
                messages.error(request, "Not Found!")
                messages.warning(request, "Please ensure the student ID is correct,<br>then try to delete it.")
                return redirect('error_404')
            
            except ValidationError as e:
                messages.error(request, "Validation Error!")
                messages.warning(request, "Please ensure the student ID is correct,<br>then try to delete it.")
                return redirect('error_404')
            
        messages.error(request, "Validation Error!")
        messages.warning(request, "ID Not Found!.")
        return redirect('error_404')
        



"""
    Student Details
"""
@method_decorator(user_passes_test(is_superuser_or_staff, 
    login_url=reverse_lazy('auth:login')), name='dispatch')
class StudentDetailsView(generic.DetailView, LoginRequiredMixin):
    model = Student
    template_name = "student/details.html"
    context_object_name = "std"

    # def get_context_data(self, *args, **kwargs):
    #     data = super().get_context_data(**kwargs)
    #     data['std'] = self.model.objects.get(id=self.kwargs['pk'])
    #     return data





"""
    Student Update
"""
@method_decorator(user_passes_test(is_superuser_or_staff, 
    login_url=reverse_lazy('auth:login')), name='dispatch')
class StudentUpdateView(generic.UpdateView, LoginRequiredMixin):
    model = Student
    template_name = "student/update.html"
    form_class = StudentForm
    context_object_name = "std"


    def get_success_url(self):
        # return reverse('admins:admin_details', kwargs={'pk': self.object.pk})
        return reverse('student:student_list')
    
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        field_errors = {field.name: field.errors for field in form}
        has_errors = any(field_errors.values())

        print("---------------------")
        print(f"Field = {field_errors}, HasErrors = {has_errors}")
        print(f"HasErrors = {has_errors}")
        print("---------------------")

        return self.render_to_response(self.get_context_data(
            form=form, 
            field_errors=field_errors, 
            has_errors=has_errors
            ))

apps/student/templates/student/delete.html
<div class="modal fade" id="delete_student" tabindex="-1" role="dialog" 
    aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="toast show align-items-center" role="alert" data-bs-autohide="false" aria-live="assertive"
            aria-atomic="true">

            <div class="d-flex">
                <div class="toast-body">Are you sure you want to delete this item?</div>
                <button class="btn-close me-2 m-auto" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="mt-2 p-3 border-top">
                <button class="btn btn-danger btn-sm" type="button" id="confirmDeleteBtn">
                    <span class="fas fa-trash me-1"></span>
                    Yes
                </button>

                <button class="btn btn-secondary btn-sm ms-2" type="button" data-bs-dismiss="modal">
                    <i class="fa-solid fa-xmark me-1"></i>
                    Close
                </button>
            </div>

        </div>
    </div>
</div>

apps/student/templates/student/filter.html
{% load static %}
<div class="modal fade" id="filter-modal" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document" style="max-width: 500px;">
      <div class="modal-content position-relative">
          <div class="position-absolute top-0 end-0 mt-2 me-2 z-index-1">
              <button class="btn-close btn btn-sm btn-circle d-flex flex-center transition-base" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <form method="get">
              <div class="modal-body p-0">
                  <div class="rounded-top-lg py-3 ps-4 pe-6 bg-light">
                      <h4 class="mb-1" id="modalExampleDemoLabel"><span class="fas fa-filter me-2 fs-1"></span>Student Filter</h4>
                  </div>
                  <div class="p-4 pb-0">
                      <div class="mb-2">
                          <label for="subject">Subject</label>
                          <div>
                              <select class="form-select select_subject" id="subject" size="1" name="subject" style="width: 100%;">
                                  <option value="">select subject</option>
                                  {% for sub_key, sub_value in subjects %}
                                  <option value="{{ sub_key }}">{{ sub_value }}</option>
                                  {% endfor %}
                              </select>
                          </div>
                      </div>

                      <div class="mb-3">
                          <div class="d-flex gap-2">
                              <div class="flex-fill">
                                  <label class="form-label" for="city">City</label>
                                  <div>
                                      <select class="form-select select_city" id="city" size="1" name="city" style="width: 100%;">
                                          <option value="">select city</option>
                                          {% for city in citys %}
                                          <option value="{{city.id}}">{{city.name}}</option>
                                          {% endfor %}
                                      </select>
                                  </div>
                              </div>

                              <div class="flex-fill">
                                  <label class="form-label" for="is_verified">Varified</label>
                                  <div>
                                      <select class="form-select select_varify" id="is_verified" size="1" name="is_verified" style="width: 100%;">
                                          <option value="">select</option>
                                          <option value="true">True</option>
                                          <option value="false">False</option>
                                      </select>
                                  </div>
                              </div>
                          </div>
                      </div>

                      <div class="mb-3">
                          <label class="form-label" for="created_at">Enroll Time Range</label>
                          <div class="d-flex gap-2">
                              <div class="flex-fill">
                                  <span class="fs--1">From</span>
                                  <input class="form-control" type="date" name="created_at_from" />
                              </div>
                              <div class="flex-fill">
                                  <span class="fs--1">To</span>
                                  <input class="form-control" type="date" name="created_at_to" />
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div class="modal-footer mt-3">
                  <button id="clear-filter" class="btn btn-secondary" type="button">
                      <i class="fa-solid fa-eraser"></i>
                      Clear
                  </button>

                  <button class="btn btn-info" type="submit" id="download-btn" name="export">
                        <span class="fas fa-solid fa-download me-1"></span>
                        Download
                  </button>

                  <button class="btn btn-primary" type="button" name="find"><i class="fa-solid fa-magnifying-glass me-1 fs-1"></i>Find</button>
              </div>
          </form>
      </div>
  </div>
</div>

apps/student/templates/student/update.html
{% extends 'layouts/master.html' %}
{% load static %}

{% block title %}
    Student | Update
{% endblock title %}

{% block styles %}
<!-- font-awesome 6.5 -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"/>

<!-- Include Select2 CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet"/>

<style>
    .select2-container--default .select2-selection--single {
        height: 40px !important;
    }

    .select2-container--default .select2-selection__rendered {
        line-height: 40px !important;
    }
</style>
{% endblock styles %}


{% block content %}

 <div class="card radius-5 col-sm-12 col-md-8 col-lg-8 col-xxl-6">

     <div class="card-header">
         <div class="d-flex align-items-center">
             <div>
                 <h6 class="mb-0">Student Update</h6>
             </div>
         </div>
     </div>

     <div class="card-body">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}


            <!-- Name input -->
            <div class="row g-1 align-items-center">
                <div class="col-3">
                    <label for="inputPassword6" class="col-form-label">
                        Name<span class="text-danger">*</span>
                    </label>
                </div>
                <div class="col-6">
                    <!-- <input type="text" id="name" class="form-control" aria-describedby="name" placeholder="Write student name" /> -->
                    {{form.name}}
                </div>
            </div>

            <!-- Roll input -->
            <div class="row g-1 align-items-center mt-1">
                <div class="col-3">
                    <label for="roll" class="col-form-label">
                        Roll<span class="text-danger">*</span>
                    </label>
                </div>
                <div class="col-6">
                    <!-- <input type="number" id="roll" class="form-control" placeholder="Write student roll" /> -->
                    {{form.roll}}
                </div>
            </div>

            <!-- Phone input -->
            <div class="row g-1 align-items-center mt-1">
                <div class="col-3">
                    <label for="phone" class="col-form-label">
                        Phone<span class="text-danger">*</span>
                    </label>
                </div>
                <div class="col-6">
                    {{form.phone}}
                </div>
            </div>

            <!-- City input -->
            <div class="row g-1 align-items-center mt-1">
                <div class="col-3">
                    <label for="city" class="col-form-label">City</label>
                </div>
                <div class="col-6">
                    {{form.city}}
                </div>
            </div>

            <!-- Birth Date input -->
            <div class="row g-1 align-items-center mt-1">
                <div class="col-3">
                    <label for="dob" class="col-form-label">
                        Birth Date
                    </label>
                </div>
                <div class="col-6">
                    {{form.dob}}
                </div>
            </div>


            <!-- Gender input -->
            <div class="row g-1 align-items-center mt-1">
                <div class="col-3">
                    <label for="gender" class="col-form-label">
                        Gender<span class="text-danger">*</span>
                    </label>
                </div>
                <div class="col-6">
                    {{form.gender}}
                </div>
            </div>

            <!-- Subject input -->
            <div class="row g-1 align-items-center mt-1">
                <div class="col-3">
                    <label for="inputPassword6" class="col-form-label">Subject</label>
                </div>
                <div class="col-6">
                    <!-- <select class="form-select" aria-label=".form-select-lg example" name="subject">
                        <option selected>Open this select menu</option>
                        <option value="1">One</option>
                        <option value="2">Two</option>
                        <option value="3">Three</option>
                      </select> -->
                      {{form.subject}}
                </div>
            </div>

            <!-- Image input -->
            <div class="row g-1 align-items-center mt-1">
                <div class="col-3">
                    <label for="inputPassword6" class="col-form-label">Image</label>
                </div>
                <div class="col-6">
                    <!-- <input type="file" id="image" class="form-control" accept="image/*" /> -->
                    {{form.image}}
                </div>
            </div>

            <!-- CV input -->
            <div class="row g-1 align-items-center mt-1">
                <div class="col-3">
                    <label for="inputPassword6" class="col-form-label">CV</label>
                </div>
                <div class="col-6">
                    <!-- <input type="file" id="cv" class="form-control" /> -->
                    {{form.cv}}
                </div>
            </div>

            <!-- Verified input -->
            <div class="row g-1 align-items-center mt-1">
                <div class="col-3">
                    <label for="is_verified" class="col-form-label">Verified</label>
                </div>
                <div class="col-6">
                    {{form.is_verified}}
                </div>
            </div>

            <!-- Description input -->
            <div class="row g-1 align-items-center mt-1">
                <div class="col-3">
                    <label for="inputPassword6" class="col-form-label">Description</label>
                </div>
                <div class="col-6">
                    <!-- <textarea class="form-control" id="description" rows="5"></textarea> -->
                    {{form.description}}
                </div>
            </div>


            <div class="form-group row mt-3">
                <div class="col-10 offset-3">
                    <button type="submit" class="btn btn-primary me-2">
                        <i class="fa fa-save me-2"></i>
                        Update
                    </button>

                    <a href="{% url 'student:student_details' std.id %}" class="btn btn-secondary">
                        <i class="fa fa-times me-2"></i>
                        Cancel
                    </a>
                </div>
            </div>
        </form>
     </div>

</div>
{% endblock content %}


{% block js %}
<!-- Include Select2 JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>


<script>
    $(document).ready(function () {
      $(".singel_select").select2({
        placeholder: "Select student city",
        allowClear: true,
      });
    });
</script>

<script>
    // Initialization for ES Users
    import { Input, Ripple, initMDB } from "mdb-ui-kit";

    initMDB({ Input, Ripple });
</script>


<script>
    var fieldErrors = {{ field_errors| safe }};

    $(document).ready(function () {

        if (fieldErrors.email.length > 0) {
            $('#id_email').addClass('is-invalid');
        }

        if (fieldErrors.phone.length > 0) {
            $('#id_phone').addClass('is-invalid');
        }

        if (fieldErrors.image.length > 0) {
            $('#id_image').addClass('is-invalid');
        }

    });
</script>

{% endblock js %}