apps/employee/urls.py
from django.urls import path
from apps.employee import views

app_name = 'employee'


urlpatterns = [
    path('create/', views.EmployeeCreateView.as_view(), name='employee_create'),
    path('list/',   views.EmployeeListView.as_view(),   name='employee_list'),
    path('delete/', views.EmployeeDeleteView.as_view(), name='employee_delete'),
    path('details/<uuid:pk>/', views.EmployeeDetailsView.as_view(), name='employee_details'),
    path('update/<uuid:pk>/',  views.EmployeeUpdateView.as_view(), name='employee_update'),

]

apps/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('apps.auth.urls',  namespace='auth')),
    path('', include('apps.dashboards.urls', namespace='dashboards')),
    path('admins/', include('apps.admin.urls', namespace='admins')),
    path('employee/', include('apps.employee.urls', namespace='employee')),
    path('student/', include('apps.student.urls', namespace='student')),


    ## Error 404 and 500 responses
    path("error-404/", TemplateView.as_view(template_name="error/404.html"), name="error_404"),
    path("error-500/", TemplateView.as_view(template_name="error/500.html"), name="error_500"),

]

django_setting_core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.urls')),


    ## For CKeditor
    # path('ckeditor/', include('ckeditor_uploader.urls')),

]




urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/employee/models.py
from django.db import models

apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from apps.users.manager import UserManager
import uuid
from apps.core.models import TimestampedModel

import datetime
import secrets
import random

## AbstructBaseUser has provite some default field ( password, last_login, is_active )
class User(AbstractBaseUser, TimestampedModel, PermissionsMixin):

    class GenderType(models.TextChoices):
        MALE   = 'male'
        FEMALE = 'female'
        OTHER  = 'other'

    class UserType(models.TextChoices):
        ADMIN    = 'admin'
        EMPLOYEE = 'employee'

    id        = models.UUIDField( primary_key = True, unique=True, default = uuid.uuid4, editable=False )
    email     = models.EmailField(
                    unique=True,
                    verbose_name="email address",
                    max_length=255,
                )
    phone     = models.CharField(
                    unique=True,
                    verbose_name="phone number",
                    max_length=30,
                    null = True,
                    blank=True
                )
    first_name = models.CharField(max_length=255, null=True, blank=True)
    last_name  = models.CharField(max_length=255, null=True, blank=True)

    gender   = models.CharField(max_length=10, choices=GenderType.choices, null=True, blank=True)
    dob      = models.DateField(null=True, blank=True) 

    image    = models.ImageField(upload_to="ProfileImage/", null=True, blank=True)

    joining     = models.DateField(null=True, blank=True)
    termination = models.DateField(null=True, blank=True)
    user_salary = models.IntegerField(default=0, null=True, blank=True)

    ## User Permission and Roll
    is_active   = models.BooleanField(default = True)
    is_admin    = models.BooleanField(default = False)
    is_verified = models.BooleanField(default = False)

    ## User Address
    address = models.TextField(null=True, blank=True)

    user_type = models.CharField(
        max_length = 10, 
        choices = UserType.choices,
        default = UserType.EMPLOYEE
    )

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    
    def __str__(self):
        return self.email
    
    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        # return True      ## Default
        return self.is_admin

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        # return True      ## Default
        return self.is_admin

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin
    
    # @property
    # def first_name(self):
    #     if self.name:
    #         parts = self.name.rsplit(" ", 1)
    #         return parts[0]

    # @property
    # def last_name(self):
    #     if self.name:
    #         parts = self.name.rsplit(" ", 1)
    #         return parts[1] if len(parts) > 1 else ""

    @property
    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"
    
    @property
    def name(self):
        return f"{self.first_name} {self.last_name}"
    

    @property
    def age(self):
        if self.dob:
            today = datetime.date.today()
            age   = today.year - self.dob.year - ((today.month, today.day) < (self.dob.month, self.dob.day))
            return age
        else:
            return None

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

apps/employee/views.py
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy

from django.contrib.auth import get_user_model
User = get_user_model()

from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sessions.models import Session
from django.contrib import messages

from django.utils.decorators import method_decorator
from django.utils import timezone

from django.db.models.functions import Concat
from django.db.models import Q, Count, F, Value as V, CharField
from django.db.models.functions import ExtractMonth, ExtractYear

from django.http import HttpRequest, HttpResponse, JsonResponse, Http404, HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage
from django.core.exceptions import ValidationError

from datetime import datetime, timedelta
from random import randint

from django.views import View
from django.views import generic

## Custom 
from django_setting_core.permission import is_superuser_or_staff, is_superadmin
from apps.core.utils2 import CustomPaginator, ExcelDataDownload
from apps.employee.forms import EmployeeCreationForm, EmployeeUpdateForm


"""
    Employee Create
"""
@method_decorator(user_passes_test(is_superuser_or_staff, 
    login_url=reverse_lazy('auth:login')), name='dispatch')
class EmployeeCreateView(generic.CreateView, LoginRequiredMixin):
    model = User
    form_class = EmployeeCreationForm
    template_name = "employee/create.html"
    success_url = reverse_lazy('employee:employee_list')

    # def form_valid(self, form):
    #     form.save()
    #     return super().form_valid(form)

    def form_invalid(self, form):
        field_errors = {field.name: field.errors for field in form}
        has_errors = any(field_errors.values())

        print("---------------------")
        print(f"Field = {field_errors}, HasErrors = {has_errors}")
        print(f"HasErrors = {has_errors}")
        print("---------------------")

        return self.render_to_response(self.get_context_data(
                form = form, 
                field_errors = field_errors, 
                has_errors   = has_errors
            ))
    



"""
    Employee List
"""
@method_decorator(user_passes_test(is_superuser_or_staff, 
    login_url=reverse_lazy('auth:login')), name='dispatch')
class EmployeeListView(View, LoginRequiredMixin):
    template_name = "employee/list.html"
    obj_per_page = 10

    def get_queryset(self):
        queryset = User.objects.filter(
                user_type = User.UserType.EMPLOYEE
            ).order_by('-created_at').exclude(is_admin=True)

        search_query = self.request.GET.get('search', '')

        if search_query:
            queryset = queryset.annotate(
                full_name = Concat(
                    'first_name', V(' '), 'last_name', output_field=CharField()
                )
            ).filter(
                Q(id__icontains = search_query)  
                | Q(first_name__icontains = search_query)  
                | Q(last_name__icontains  = search_query)  
                | Q(full_name__icontains  = search_query)  
                | Q(email__icontains = search_query) 
                | Q(phone__icontains = search_query)
            )

            # queryset = [user for user in queryset if search_query.lower() in (user.first_name + ' ' + user.last_name).lower()]

        return queryset


    def get(self, request, *args, **kwargs):
        queryset = self.get_queryset()
        query_params = {}

        ## NOTE:- Filter values from the GET parameters
        is_verified = request.GET.get('is_verified', '')
        if is_verified != '':
            queryset = queryset.filter(is_verified=bool(int(is_verified)))
            query_params['is_verified'] = is_verified

        joining_from = self.request.GET.get('joining_from', '')
        if joining_from:
            queryset = queryset.filter(joining__gte=joining_from)
            query_params['joining_from'] = joining_from

        joining_to = self.request.GET.get('joining_to', '')
        if joining_to:
            queryset = queryset.filter(joining__lte=joining_to)
            query_params['joining_to'] = joining_to

        created_at_from = self.request.GET.get('created_at_from', '')
        if created_at_from:
            queryset = queryset.filter(created_at__gte=created_at_from)
            query_params['created_at_from'] = created_at_from

        created_at_to = self.request.GET.get('created_at_to', '')
        if created_at_to:
            queryset = queryset.filter(created_at__lte=created_at_to)

            query_params['created_at_to'] = created_at_to

        query_params_string = '&'.join([f"{key}={value}" for key, value in query_params.items()])


        # if created_at != '':
        #     if 'to' in created_at:
        #         from_date_str, to_date_str = created_at.split(" to ")
        #         from_date = datetime.strptime(from_date_str, "%d/%m/%y")
        #         to_date   = datetime.strptime(to_date_str, "%d/%m/%y")

        #         queryset = queryset.filter(created_at__range=[from_date, to_date])
        #     else:
        #         try:
        #             specific_date = datetime.strptime(created_at, '%d/%m/%y') 
        #             queryset = queryset.filter(created_at__date=specific_date) # Handle specific date
        #         except ValueError:
        #             pass # Handle invalid date format

        # ## NOTE:- Check if the export button is clicked
        export_data = ''

        if 'export' in request.GET:
            export_data = queryset
        
        elif 'export_all' in request.GET:
            export_data = User.objects.all()

        if export_data:

            # Prepare the data for Excel export
            excel_data = [
                ['No', 'Name', 'Email', 'Phone', 'User Type', 'Join Date', 'Create Date', 'Updated Date', 'Verification Status'],
            ]

            for index, user in enumerate(export_data, start=1):
                joining_date = user.joining.strftime('%d-%m-%Y') if user.joining else ''  # Check if joining is not None
                excel_data.append([
                    index,
                    user.name,
                    user.email,
                    user.phone,
                    user.user_type.capitalize() if user.user_type else '',
                    joining_date,
                    user.created_at.strftime('%d-%m-%Y %I:%M:%S %p'),
                    user.updated_at.strftime('%d-%m-%Y %I:%M:%S %p'),
                    'Verified' if user.is_verified else 'Unverified',
                ])

            
            excel_exporter = ExcelDataDownload(excel_data, filename='UsersData_export')
            return excel_exporter.generate_response()


        ## NOTE:- For Pagination
        custom_paginator = CustomPaginator(queryset, self.obj_per_page)
        paginated_data = custom_paginator.get_paginated_data(request)

        context = {
            'employee': paginated_data['page_obj'],
            'page_obj': paginated_data['page_obj'],
            'page_range': paginated_data['page_range'],
            'queryset_count': queryset.count(),
            'query_params_string': query_params_string,
        }

        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):

        if 'delete_list' in request.POST:
            # Split the string into a list of IDs
            delete_ids = request.POST.get('delete_id_list', '').split(',')  

            # Convert the IDs to integers (This is not need because ID is uuid)
            # delete_ids = [int(id) for id in delete_ids if id.isdigit()]  

            # Delete the employee with the selected IDs
            User.objects.filter(id__in=delete_ids).delete()

        return redirect('employee:employee_list')




"""
    Employee Delete
"""
@method_decorator(user_passes_test(is_superuser_or_staff, 
    login_url=reverse_lazy('auth:login')), name='dispatch')
class EmployeeDeleteView(generic.DeleteView, LoginRequiredMixin):
    model = User
    success_url = reverse_lazy('employee:employee_list')

    def post(self, request, *args, **kwargs):
        user_id = request.POST.get('user_id', None)
      
        if user_id is not None:
            try:
                user = User.objects.get(id = user_id)
                if user:
                    user.delete()
                    return redirect(self.success_url)
            except User.DoesNotExist:
                messages.error(request, "User Is Not Found!")
                messages.warning(request, "Please ensure the employee ID is correct,<br>then try to delete it.")
                return redirect('error_404')
            
            except ValidationError as e:
                messages.error(request, "Validation Error!")
                messages.warning(request, "Please ensure the employee ID is correct,<br>then try to delete it.")
                return redirect('error_404')
            
        messages.error(request, "Validation Error!")
        messages.warning(request, "ID Not Found!.")
        return redirect('error_404')
        
    # def delete(self, request, *args, **kwargs):
    #     try:
    #         user_id = self.kwargs['pk']  
    #         print("-------------------")
    #         print(f"Deleting user with ID: {user_id}")
    #         print("-------------------")
    #         return super().delete(request, *args, **kwargs)  # Let the parent class handle deletion
    #     except User.DoesNotExist:
    #         messages.error(request, "User Is Not Found!")
    #         return redirect('error_404')



"""
    Employee Details
"""
@method_decorator(user_passes_test(is_superuser_or_staff, 
    login_url=reverse_lazy('auth:login')), name='dispatch')
class EmployeeDetailsView(generic.DetailView, LoginRequiredMixin):
    model = User
    template_name = "employee/details.html"

apps/employee/templates/employee/create.html
{% extends 'layouts/master.html' %}
{% load static %}

{% block title %}
    Employee | Create
{% endblock title %}

{% block styles %}
<style>

</style>
{% endblock styles %}

{% block content %}


<div class="card mb-3">
    <div class="card-header">
        <div class="row flex-between-end">
            <div class="col-auto align-self-center">
                <h5 class="mb-0" data-anchor="data-anchor">Employee Create</h5>
            </div>
        </div>
    </div>
    <div class="card-body bg-light">
        <div class="tab-content">
            <div class="tab-pane preview-tab-pane active" role="tabpanel"
                aria-labelledby="tab-dom-68f59ccc-3b08-4ccc-af2d-26fccf62a3ae"
                id="dom-68f59ccc-3b08-4ccc-af2d-26fccf62a3ae">
                <form class="row g-3" method="post" enctype="multipart/form-data">
                    <!-- Display form-level errors if they exist -->
                    {% if form.non_field_errors %}
                    <ul class="errorlist">
                        {% for error in form.non_field_errors %}
                        <li class="error-message">{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}

                    {% csrf_token %}


                    <div class="col-lg-6 mb-3">
                        <label class="form-label" for="name">First Name</label>
                        <strong class="text-danger">*</strong>
                        {{form.first_name}}
                    </div>

                    <div class="col-lg-6 mb-3">
                        <label class="form-label" for="name">Last Name</label>
                        <strong class="text-danger">*</strong>
                        {{form.last_name}}
                    </div>

                    <div class="col-lg-6 mb-3">
                        <label class="form-label" for="email">Email</label>
                        <strong class="text-danger">*</strong>
                        {{ form.email }}
                        {% for error in form.email.errors %}
                        <div class="invalid-feedback">
                            {{ error }}
                        </div>
                        {% endfor %}
                    </div>


                    <div class="col-lg-6 mb-3">
                        <label class="form-label" for="phone">Phone Number</label>
                        <strong class="text-danger">*</strong>
                        {{form.phone}}
                        {% for error in form.phone.errors %}
                        <div class="invalid-feedback">
                            {{ error }}
                        </div>
                        {% endfor %}
                    </div>

                    <div class="col-lg-6 mb-3">
                        <label class="form-label" for="user_type">Gender</label>
                        {{form.gender}}
                    </div>

                    <div class="col-lg-6 mb-3">
                        <label class="form-label" for="user_type">Birth Date</label>
                        <strong><span class="fs--2 ms-1">(MM/DD/YYYY)</span></strong>
                        </label>
                        {{form.dob}}
                    </div>

                    <div class="col-lg-6 mb-3">
                        <label class="form-label d-block" for="user_img">Profile Image</label>
                        {{form.image}}
                    </div>

                    <div class="col-lg-6 mb-3">
                        <label class="form-label d-block" for="joining">Joining Date</label>
                        {{form.joining}}
                    </div>

                    <div class="col-lg-6 mb-3">
                        <label class="form-label d-block" for="joining">Salary</label>
                        {{form.user_salary}}
                    </div>

                    <div class="col-lg-8 mb-3">
                        <label class="form-label d-block" for="user_img">Address</label>
                        {{form.address}}
                    </div>

                    <div class="col-md-4">
                        <label class="form-label" for="validationCustom01">
                            Is Verified
                        </label>
                        <div class="form-check form-switch">
                            <input class="form-check-input" id="id_is_verified" type="checkbox" name="is_verified" checked="" />
                        </div>
                    </div>

                    <div class="col-12 d-flex justify-content-end">
                        <a class="btn btn-secondary" href="{% url 'employee:employee_list' %}">
                            <i class="fa fa-times me-2"></i>
                            Cancel
                        </a>
                        <button class="btn btn-primary ms-2" type="submit">
                            <i class="fa fa-save me-2"></i>
                            Submit
                        </button>
                    </div>

                </form>

            </div>
        </div>
    </div>
</div>

<!-- <input type="file" style="border-style: dotted;"> -->
{% endblock content %}


{% block js %}
<script>
    var fieldErrors = {{ field_errors| safe }};

    $(document).ready(function () {

        if (fieldErrors.email.length > 0) {
            $('#id_email').addClass('is-invalid');
        }

        if (fieldErrors.phone.length > 0) {
            $('#id_phone').addClass('is-invalid');
        }

        if (fieldErrors.image.length > 0) {
            $('#id_image').addClass('is-invalid');
        }

    });
</script>

<script>

    // Setup handling for profile image
    setupImageHandling('user_img', 'show_select_image_profile', 'remove_profile_image', '{% static "assets/img/upload-image2.2.png" %}');

    // Setup handling for cover image
    setupImageHandling('user_cov_img', 'show_select_image_cover', 'remove_cover_image', '{% static "assets/img/upload-image2.2.png" %}');
</script>

{% endblock js %}

apps/employee/templates/employee/delete.html
<div class="modal fade" id="delete-{{emp.id}}" tabindex="-1" role="dialog" 
    aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="toast show align-items-center" role="alert" data-bs-autohide="false" aria-live="assertive"
            aria-atomic="true">

            <form action="{% url 'employee:employee_delete' %}" method="POST">
                {% csrf_token %}
                <div class="d-flex">
                    <div class="toast-body">Are you sure you want to delete this item?</div>
                    <button class="btn-close me-2 m-auto" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <input type="hidden" name="user_id" value="{{emp.id}}">

                <div class="mt-2 p-3 border-top">
                    <button class="btn btn-danger btn-sm" type="submit">
                        <span class="fas fa-trash me-1"></span>
                        Delete
                    </button>
    
                    <button class="btn btn-secondary btn-sm ms-2" type="button" data-bs-dismiss="modal">
                        <i class="fa-solid fa-xmark me-1"></i>
                        Close
                    </button>
                </div>

            </form>

        </div>
    </div>
</div>

apps/employee/templates/employee/filter.html
{% load static %}

<div class="modal fade" id="filter-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document" style="max-width: 450px">
      <div class="modal-content position-relative">
        <div class="position-absolute top-0 end-0 mt-2 me-2 z-index-1">
          <button class="btn-close btn btn-sm btn-circle d-flex flex-center transition-base" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form method="get">

          <div class="modal-body p-0">
              <div class="rounded-top-lg py-3 ps-4 pe-6 bg-light">
                  <h4 class="mb-1" id="modalExampleDemoLabel">
                    <span class="fas fa-filter me-2 fs-1"></span>Employee Filter
                  </h4>
              </div>
              <div class="p-4 pb-0">
  
                  <div class="mb-2">
                      <label for="is_verified">Is Verified</label>
                      <select class="form-select js-choice" id="is_verified" size="1" name="is_verified"
                        data-options='{"removeItemButton":true,"placeholder":true}'>
                          <option value="" 
                            {% if not request.GET.is_verified %}selected{% endif %}>
                            select
                          </option>
                          <option value="1" 
                            {% if request.GET.is_verified == "1" %}selected{% endif %}>
                            True
                          </option>
                          <option value="0" 
                            {% if request.GET.is_verified == "0" %}selected{% endif %}>
                            False
                          </option>
                      </select>
                  </div>
      
                  <div class="mb-3">
                    <label class="form-label" for="created_at">Joining Time Range</label>
                    <!-- <input class="form-control datetimepicker" id="created_at" type="text" 
                       placeholder="d/m/y to d/m/y" name="joining" 
                       data-options='{"mode":"range","dateFormat":"d/m/y","disableMobile":true,"locale":"bn"}' 
                       value="{{ request.GET.joining }}"> -->
                    <div class="d-flex gap-2">
                        <div class="flex-fill">
                          <span class="fs--1">From</span>
                          <input class="form-control" type="date" name="joining_from" value="{{request.GET.joining_from}}">
                        </div>
                        <div class="flex-fill">
                          <span class="fs--1">To</span>
                          <input class="form-control" type="date" name="joining_to" value="{{request.GET.joining_to}}">
                        </div>
                    </div>
                  </div>
      
                  <div class="mb-3">
                      <label class="form-label" for="created_at">Enroll Time Range</label>
                      <!-- <input class="form-control datetimepicker" id="created_at" type="text" 
                         placeholder="d/m/y to d/m/y" 
                         data-options='{"mode":"range","dateFormat":"d/m/y","disableMobile":true,"locale":"bn"}' name="created_at" 
                         value="{{ request.GET.created_at }}"> -->

                      <div class="d-flex gap-2">
                          <div class="flex-fill">
                            <span class="fs--1">From</span>
                            <input class="form-control" type="date" name="created_at_from" value="{{request.GET.created_at_from}}">
                          </div>
                          <div class="flex-fill">
                            <span class="fs--1">To</span>
                            <input class="form-control" type="date" name="created_at_to" value="{{request.GET.created_at_to}}">
                          </div>
                      </div>
                  </div>
      
              </div>
          </div>
          <div class="modal-footer mt-3">
              <a class="btn btn-secondary" href="{% url 'employee:employee_list' %}">
                <i class="fa-solid fa-eraser"></i>
                Clear
              </a>
              <button class="btn btn-info" type="submit" name="export">
                <span class="fas fa-solid fa-download me-1"></span>
                <!-- Export -->
                Download
              </button>
              <button class="btn btn-primary" type="submit">
                <i class="fa-solid fa-magnifying-glass me-1 fs-1"></i>Find
              </button>
          </div>
        </form>
      
      </div>
    </div>
</div>